spring.application.name=wms

# PostgreSQL 연결 설정 (맨 뒤의 wms 자리에 본인이 만든 DB 이름을 적으세요)
spring.datasource.url=jdbc:postgresql://localhost:5432/wms
spring.datasource.username=postgres
spring.datasource.password=1234

# 자바 코드를 읽어서 PostgreSQL에 테이블을 자동으로 만들어주는 옵션
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true